project:
  type: website
  output-dir: docs

website:
  title: "Maren Rusk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Science Projects"
        menu: 
         # - href: comppoli.qmd
         - href: sqldata.qmd
         - href: simulationanalysis.qmd
         - href: textanalysis.qmd
         - text: Olympics Exploration
           href: visualization1.html
         - text: Global Cheeses
           href: visualization2.html
      - href: presentation.qmd
           

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
    page-layout: full



