project:
  type: website
  output-dir: docs

website:
  title: "Maren Rusk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Data Viz"
        menu: 
         - text: Olympics
           href: visualization1.html
         - text: Cheese
           href: visualization2.html
      - href: textanalysis.qmd
           

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



