project:
  type: website
  output-dir: docs

website:
  title: "Maren Rusk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Tidy Tuesday Data Vizualizations"
        menu: 
         - text: Olympics
           href: visualization1.html
         - text: Cheese
           href: visualization2.html
      - href: textanalysis.qmd
      - href: simulationanalysis.qmd
      - href: sqldata.qmd
           

format:
  html:
    theme: superhero
    toc: true
    page-layout: full



