---
title: "Electoral Systems and Policy Direction"
description: Do PR Systems Correspond with More Progressive Policies?
author: Maren Rusk
date: December 11, 2024
format: html
execute:
  warning: false
  message: false
---

Introduction
In the United States and other majoritarian nations, numerous left vs. right political controversies revolve around the rejection of progressive policy ideals that are unanimously accepted in many western consensus democracies. Why, then, do these contemporary ideals that have been widely supported and implemented in other democracies remain so controversial and difficult to realize in the US and other similarly massive anglophone powers? Examining relevant differences in political systems between these nations reveals a key structural divergence in the type of electoral system employed by these democracies. Many heterogeneous consensus democracies utilize proportional representation electoral systems that promote proportionality of vote to seat representation by delegating accurate proportions of seats to several parties based on the share of the vote they receive. While this is one of several differences between these nations, electoral system variation is particularly notable because it directly relates to the degree of disparity between public priorities and policy outputs.
	In this research paper, I will attempt to corroborate this relationship and investigate how differences between electoral system structures might influence representation in terms of government composition and eventually, at the policy level. The exploration will base around the established phenomenon that representational advantages of nations under proportional representation systems increase the influence of ideologically left-leaning parties in the national government. Combining these insights leads to consideration of the research question: Are proportional representation electoral systems associated with a shift to the left in the policy outcomes of their resulting governments? Through analysis of existing literature and electoral system and policy data, I find a measurable and significant leftward tilt in several policy areas in PR systems compared to plurality systems, partially confirming my affirmative hypothesis.
Overview & Literature Review 
	Proportional representation electoral systems are cornerstones of consensus democracies. They effectively exemplify a power sharing model by creating more inclusive and cooperative governments composed of diverse parties. According to Lijphart (2012), “the basic aim of proportional representation is to represent both majorities and minorities and, instead of overrepresenting or underrepresenting any parties, to translate votes into seats proportionally”. There are three main forms of elections used by PR systems to promote this proportionality in government representation. List systems allow voters to cast a ballot for a list of candidates nominated by a party, while mixed-member proportional systems require each voter to select both a district candidate and a party list. Meanwhile, single transferable vote systems enable voters to rank candidates, and delegate seats proportionally to candidates with highest rankings (Lijphart, 2012). By utilizing multimember districts and proportional translation of seats, these systems facilitate diverse representation across heterogeneous nations. On the other hand, majoritarian electoral structures include plurality or majority methods, where elections are conducted in single-member districts with a ‘winner-take-all’ format that encourages two-party systems. By delegating all power to the party or candidate that receives the most votes, these elections lead to overrepresentation of the majority party and underrepresentation of minority voters. 
The contrasting electoral ideals of consensus PR systems and majoritarian plurality systems create disparities in the relative representative proportionality of different nations’ electoral systems. In fact, Lijphart found a “strikingly clear dividing line” between the degrees of disproportionality in vote to seat translations between proportional and majoritarian systems. The most direct explanatory factor for this difference is district magnitude. While majoritarian systems boast single-member districts that upset the vote to seat ratio by allowing only votes toward a single party to count in each district, multimember districts employed by PR systems minimize this malapportionment by allowing for proportional allocation of seats to preexisting geographical units (Lijphart, 2012). Exclusively in PR systems, larger district magnitudes translate to more proportionality. For instance, an election conducted in a single nationwide district eliminates any possibility of malapportionment because the percentage of votes won by each party will directly dictate the percentage of seats won on the national level. Furthermore, in addition to ideological representation, larger district magnitudes also elicit an increase in descriptive representation. For example, research in Western Europe and Costa Rica found a distinct gap in women’s representation in national legislatures between nations with single-member district electoral systems and those with multimember PR systems (Matland & Taylor, 1997). The simple explanation for this is that larger district magnitudes allow for more viable parties and candidates, thus “encouraging the nomination and election of more female candidates and likely more balanced sets of candidates in general” (Bernauer et al., 2015). Therefore, established research on several indicators of representation concludes that PR elections generally result in governments that better reflect their citizenry, both ideologically and descriptively.
The notion that PR systems generate more representative governments than other electoral systems is well substantiated. However, additional studies provide evidence that this representative advantage facilitates the election of more ideologically left-leaning governments, compared to those in majoritarian systems. This is likely related to increased inclusion of left-leaning or moderate groups that tend to be underrepresented in other electoral systems. PR systems allow for a larger range of parties, thus more effectively covering the whole ideological range, including the progressive parties preferred by minority groups in the “political corner” (Bernauer et al., 2015). Voters are not only given the option to cast a ballot for the party they align with, but also a much higher chance of this party winning seats in government without requiring a majority of the vote. These factors increase the incentive for minority groups to vote, and the proportionality in the translation of their votes to seats in government. Furthermore, this increase in party representation also influences middle class voters, as in two-party systems, they tend to swing toward right-wing parties in order to avoid anticipated redistributive consequences of the left (Dӧring & Manow, 2015). With PR systems presenting more viable parties that represent their preferences, middle class voters are more likely to vote for center or center-left parties than right-wing parties, thus shifting the overall makeup of the elected government to the left. Another key advantage of PR systems for left-wing parties is that the previously discussed decrease in malapportionment allows for more equitable representation of urban voters. According to Dӧring & Manow, “low-income earners are more likely to live in densely populated areas”. With income being a strong predictor of voting choice according to both Dӧring & Manow and Bernauer et al., a more fair vote to seat translation for urban voters can have a large impact. Where in majoritarian systems many urban votes are deemed “wasted” due to the left winning these districts by large margins and narrowly losing many rural districts, the inherent proportionality of PR systems mitigates this issue, making it far more likely for left-wing parties to win additional seats.
While there is considerable indication that PR systems produce a leftward shift in terms of the governments’ ideological composition, proof of a consequential increase in left-leaning policy outcome is less than prevalent. Across various studies, findings are mixed, and scarcely any research shows a complete leftward policy adjustment. One study on Norwegian governments found that small representation shifts resulted in larger left-wing parties, bringing about increased property taxation and higher childcare spending, but had opposite effects on elderly care spending and none on public goods (Fiva et al., 2018). Additionally, a study examining Swiss data determined that “proportional systems shift spending toward broad goods (e.g. education and welfare benefits) but decrease spending on targetable goods (e.g. roads and agricultural subsidies)” (Funk & Gathmann, 2009). These inconsistencies in policy results across categories may relate to the notion that PR coalition governments tend to be less responsive to public preferences and opinion change than single-party majoritarian governments (Wlezien & Soroka, 2015). With less coordination and direct accountability to the public than single-party governments, governments under PR frameworks are more likely to stray from public opinion, and thus the relationship between ideology and policy might not be quite as linear. However, these studies also focus exclusively on state and local governments in specific countries, making it challenging to ascertain whether similar effects occur at the national level when a larger range of democracies is considered. 

Theory and Hypothesis
Overall, review of relevant literature strongly indicates a positive influence of PR systems on government representation and left-leaning composition. Assuming this relationship holds true, consideration of the connection between this leftward adjustment and actual policy outcomes is warranted. At first glance, it may seem trivial that a comparatively left-leaning government would implement progressive policies. However, other confounding factors of PR systems and consensus democracies tend to curb this tendency in comparison to the more straightforward trajectory of single-party governments. This is evident in the mixed results of several studies that looked into policy differences resulting from electoral system shifts in the state and local governments of particular countries. While these results provide valuable information that can likely be generalized to some extent, I am interested in broadening this topic to a comparison of policy direction between democratic nations over the periods in which they have had particular electoral systems. Hence, I hypothesize that due to the demonstrated increase in representation under PR systems, governments operating within PR frameworks will, on average, exhibit a leftward shift in policy compared to their majoritarian counterparts.

Methods and Results

	In order to test this hypothesis, I examined a combination of data from the Comparative Political Data Set (Armingeon et al., 2024), which listed data on electoral systems and several policy variables for 36 democratic nations between 1980 and 2023, and the OECD Data Explorer (OECD), which contained similarly formatted minimum wage and corporate tax rate data. I compiled this data into a single set containing mean policy indicators across all years for each country. This allowed for the facilitation of comparisons between electoral systems on social, labor, and tax policy using the following indicators: 
Social spending: Total public and mandatory private social expenditure as a percentage of GDP.
Job Creation: Public and private mandatory expenditure on direct job creation (usually in the public or non-profit sector) as a percentage of GDP.
Employment Protection: Employment protection strictness provided through legislation and as a result of enforcement processes (scale of 0-6; higher values indicate stricter employment protection).
Minimum Wage: Real minimum wages at constant prices (in USD, PPP converted).
Corporate Taxes: Statutory corporate income tax rate (%).
Because larger social and labor expenditures, employment protection, minimum wages, and corporate tax rates are ideologically left-leaning policies, I classified higher values as further left, and lower values as further right.
I began the data analysis by visualizing the differences between the three types of electoral systems categorized by the CPDS dataset: single-member plurality systems, mixed/alternative systems, and PR systems. For each policy variable, I created column charts displaying the mean over the given years for each country, arranged and colored by type of electoral system (Figure 1). These visualizations showed mixed results - for some variables (total social expenditure, job creation, employment protection), countries with PR systems tended to have slightly larger means. Others were either too similar to tell, or showed the opposite relationship, conflicting with my hypothesis. Outliers, particularly among the mixed system category, clouded these results visually. 
Hence, to make the comparisons more visually understandable, I created notched box plots for each variable (Figure 2). I initially grouped the plurality and mixed systems into one category in order to set up a direct comparison between pure PR and non-PR systems, and then created side-by-side box plots displaying distributions of these countries versus PR countries. I did not find any of the median differences to be significant, but the total social expenditure boxplots appeared very close to having non-overlapping notches. I continued by performing a t-test for this variable to check for a statistically significant difference in means between PR and non-PR systems. However, this did not elicit any significant result - in fact, the means were closer together than the medians, likely due to the mixed system outliers and small sample size, resulting in a p-value of 0.2.
Next, I repeated this process after removing the countries listed as having mixed/alternative systems in order to look for a significant difference between pure plurality systems and pure PR systems. Here, I found both significant median differences with notched boxplots (Figure 3) with no overlap for mean total social expenditure, job creation spending, and employment protection strictness, and significant p-values from t-tests across each of these variables. The summary statistics are displayed in Figure 4, suggesting a statistically significant difference between policy means for PR and plurality governments for each of these three variables.

Discussion 
	The results of my analysis offer mixed support for my hypothesis. Overall, I did not find overwhelming evidence that policies were more left-leaning as a whole. Both minimum wage and corporate tax rate, variables I consider to be some of the strongest indicators of policy ideology, showed no sign of leftward tilt for PR systems compared to plurality systems. In fact, the median minimum wage and tax rate for plurality framework countries were firmly higher than those for PR nations. However, for total social expenditure, job creation, and employment protection, the analysis showed significant increases in mean policy mean for PR systems compared to plurality systems. With respective p-values of 0.011, 0.002, and 3.403 x 10^-8, we appear to have statistically significant evidence that these means are larger among the population, and therefore more progressive (‘leftist’), in PR systems. 
However, considerations of the validity of these tests must be taken into account. For instance, although the t-tests reported statistically significant results, these p-values came from plurality systems sample sizes of only 3-4. This decreases the validity because t-tests assume normality and homogeneity which is difficult to verify with such a small amount of data. Additionally, one of these few plurality system data points was the 1960-1995 period of New Zealand before it switched to a PR system. Since means were taken across all years where data was available, which extended beyond 1995 for most countries, differences in overall policy trends over years might significantly impact the average policy positions calculated for plurality systems. This could expand bias across the entire dataset, since the trend I discovered might have only existed for a certain period of time that raised the overall mean across years. Finally, there is a potential bias raised in the possibility that countries that choose to implement PR systems are more liberal in the first place, since proportional representation reflects a desire to ensure fair representation among diverse political, ethnic, or social groups.
It also must be acknowledged that my original calculations between PR and non-PR systems as classified by the CPDS did not yield any significant results, and an increase in leftist policy was only found when the countries in the middle “mixed” category were removed. However, it does make some sense to omit this data, as the simplicity of the dataset’s classification reveals no information about how neutral each of these systems are. Some of them may lean heavily majoritarian, while others may more closely resemble PR. If countries like this were initially counted as non-PR, this could explain why the mixed system category had lots of outliers and inconsistent data that balanced out the averages between PR and non-PR countries.
	Finally, assuming these results do have some significance, there are several reasons why the well-supported claim about an increase in left-leaning ideological representation in government does not appear to fully translate to a leftward shift in policy. As previously discussed, Wlezien and Soroka (2015) suggest that a lack of direct accountability to the public in the coalition governments formed by PR systems creates discrepancies between the post-election composition of the government and the policies that materialize throughout the term. This means that while the ideological bend of the government might match up better with that of the public in PR systems, PR governments might also be less responsive to public opinion change and thus may not remain as representative between elections. Furthermore, majoritarian systems like the ones in my dataset (US, UK, and Canada) might have other underlying reasons for implementing higher corporate taxes or minimum wages, such as economic productivity or globalization-driven labor standards. Lastly, according to Lijphart’s findings on vote to seat disproportionality by country, the four plurality system countries that I examined, New Zealand, Canada, the US, and the UK, are among some of the lowest ranked for disproportionality of all existing plurality systems. Many small countries with plurality systems and “unusually small legislatures” that were not included in my data have much larger degrees of disproportionality (2012). Perhaps expanding this research to include these smaller majoritarian nations could elicit a more noticeable relationship between electoral system and policy direction.

Conclusion
	In conclusion, examination of democracies with varying electoral systems across several decades yields a potentially significant positive relationship between the proportionality of electoral systems and progressive policies on social spending, job creation, and labor protections. While this association was not observed across all policy variables, there may be potential for these findings if the scope of data was increased to include a full range of democracies with majoritarian electoral systems. Moreover, I only looked at select policy categories, but if a more thorough range were examined, it may be possible to obtain an index in order to investigate an overall leftward lean in policy, rather than examining each variable separately. Nonetheless, the significance of my findings provide insight into how a country’s electoral system can impact which groups receive representation in government and therefore policy outcomes favorable to their preferences. Ultimately, these discoveries underscore the importance of electoral design in shaping the depth of political inclusion and the consequential representative accuracy of governments and policy across the globe.

Data Visualizations

Figure 1. Flipped column plots with three electoral system groupings.




Figure 2. Notched Box Plots for PR vs non-PR systems.
Notches represent a 95% confidence interval around the median.













Figure 3. Notched box plots for plurality vs PR systems














Figure 4. Summary statistics for t-tests. 
group 0 = plurality systems, group 2 = pr systems

Mean Total Social Expenditure
t = -3.0008, df = 12.598, p-value = 0.01054
alternative hypothesis: true difference in means between group 0 and group 2 is not equal to 0
95 percent confidence interval:
 -4.8907140 -0.7886571
sample estimates:
mean in group 0 mean in group 2 
       17.42898        20.26867

Mean Job Creation Expenditure
t = -3.4894, df = 21.833, p-value = 0.002093
alternative hypothesis: true difference in means between group 0 and group 2 is not equal to 0
95 percent confidence interval:
 -0.09976525 -0.02536426
sample estimates:
mean in group 0 mean in group 2 
     0.01775154      0.08031629

Mean Employment Protection Strictness
t = -7.8287, df = 24.995, p-value = 3.483e-08
alternative hypothesis: true difference in means between group 0 and group 2 is not equal to 0
95 percent confidence interval:
 -1.984702 -1.157946
sample estimates:
mean in group 0 mean in group 2 
      0.2964286       1.8677527
